name: second action
on: [push,workflow_dispatch]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Bring Code
        uses: actions/checkout@v3
      - name: Install node JS
        uses: actions/setup-node@v4
      - name: install packages
        run: npm install
      - name: test code
        run: npm test
      - name: build code
        run: npm run build
